### ISSUE TITLE
GUI crashes when I try to run it

### ISSUE THREAD

**Issue by giovannifi** [GoBig87/NordVpnLinuxGUI#1] opened 2021-12-28 08:17 UTC
I tried to install your app, but it crashes when I try to run it. I run the file NordVPNLinuxGUI.sh from the command line and this is the error message I get at the very end:

Traceback (most recent call last):
   File "main.py", line 40, in <module>
     MainApp().run()
   File "/home/giovanni/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/giovanni/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "main.py", line 29, in build
     self.content.add_widget(SettingsScreen(name="settings"))
   File "/home/giovanni/NordVpnLinuxGUI/ui/screens/settings_screen.py", line 304, in __init__
     self.update_settings()
   File "/home/giovanni/NordVpnLinuxGUI/ui/screens/settings_screen.py", line 356, in update_settings
     widget = self.ids[ids]
 KeyError: 'Obfuscate'

**Comment by GoBig87** [comment] 2021-12-28 10:12
Whoops looks there’s an error with auto generating the settings.  I’ll fix it tomorrow.   Sorry there’s some issues that might pop up as I haven’t had time to do extensive testing.    I’ll try to reproduce and get a fix in soon.

**Comment by Shaolin-Twelve** [comment] 2021-12-28 14:54
As above, but I'm on Linux Mint 20 with Cinnamon Desktop 4.6.7.

On install the wheel was not made, so after the ./installer.sh script failed on that part but succeeded with the rest of the install, I tried ;

pip install wheel (in the source directory)

which created the wheel successfully.

I then cut and paste the    ./NordVpnLinuxGUI    command from the instructions on the webpage, but this failed.

On my system it should be   ./NordVpnLinuxGUI.sh     to work, but this too failed until I noticed that the file it was referring to is named   ./NordVPNLinuxGUI.sh .  As this looks to be a typo, I renamed the file to ./NordVpnLinuxGUI.sh, and it then ran with the same issues as giovannifi above.

This project looks to be exactly what I've been hoping for to better control NordVpn on Linux.

Thank you for your efforts.

I think this could become the very best client app available for NordVpn on Linux, it certainly looks like you're going for gold with this.

I look forward to seeing this work as intended.

**Comment by GoBig87** [comment] 2021-12-29 00:13
@giovannifi it should be fixed with this https://github.com/GoBig87/NordVpnLinuxGUI/commit/fec847123fefdad0223e0f058a04e90c208d4d1e.

**Comment by GoBig87** [comment] 2021-12-29 00:18
@Shaolin-Twelve I fixed the read me with https://github.com/GoBig87/NordVpnLinuxGUI/commit/7ff00c5000f055d7d50f8b26211be58e675dfeec and the missing install python wheel module with https://github.com/GoBig87/NordVpnLinuxGUI/commit/c1ae61c4831ca1005b70326e4b4720731cd363d9

**Comment by Shaolin-Twelve** [comment] 2021-12-29 01:03
Thank you,

all 3 links (fec8471, 7ff00c5, & c1ae61c) worked for me, the app now launches and displays correctly.

**Comment by giovannifi** [comment] 2021-12-29 01:38
All good, it is now working for me.

thanks for that

**Closed** 2021-12-29 01:39 UTC
